language: node_js

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter

before_script:
- greenkeeper-lockfile-update
- ./cc-test-reporter before-build

after_script:
- greenkeeper-lockfile-upload

after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
- npm run ci

after_success:
- npm run codeclimate

node_js:
- "8"
- "10"
- "12"

