language: node_js

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- npm install -g codeclimate-test-reporter

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run lint
  - npm run test

before_deploy: npm run codeclimate

deploy:
  provider: script
  script: echo 'placeholder'
  on:
    tags: true

node_js:
  - "8"
  - "10"
  - "12"

