name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm i
        working-directory: ./examples/async
      - run: npm i
        working-directory: ./examples/callback
      - run: npm run lint
      - run: npm run coverage
      - uses: codecov/codecov-action@v7
        if: matrix.node-version == '24.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true
